#!/bin/bash
echo -e "+-------------------+\n| RUNNING ALL TESTS |\n+-------------------+"

	#any temp files to be stored in test/temp
	#output of testbench created in test/output. i.e per test logfiles
	#once all tests run, print CSV file to stdout, with each row corresponding to one execution of Simulator under test.

printf "TEST,RETCODE\n" >> test/output/log.csv

# for file in test/input/*.bin
# do
	# name=${file##*/}	
	name="lwr5.bin"
	#filename="${file%.*}.s"
	filename="test/input/lwr5.s"

	values=()

	#Read file values
	while IFS= read -r line || [[ -n "$line" ]]; do
		# reading each line
		value="${line//#}"
		values+=("$value")
	done < $filename

	no_path_filename=$(basename -- "$filename")
	test_id="${no_path_filename%.bin}"
	operation=${values[0]}
	sim_code=${values[1]}
	user_id=${values[2]}
	comments=${values[3]}
	getc=${values[4]}
	expected_putc=${values[5]}

	#Run test
	$input | ./bin/mips_simulator test/input/${name}

	if [ -f "$getc" ]; then
      RETCODE=$(cat "$getc" | "$1" "test/input/${name}")
  else
			echo $getc
      RETCODE=$(echo $getc | "$1" "test/input/${name}")
			echo $RETCODE
  fi

	if [ $RETCODE -ge 128 ]; then
		RETCODE=$((RETCODE-256))
	fi

	NUMTESTS=0
	COUNT=0

	printf  "${name},${RETCODE}\n" >> test/output/log.csv
	echo "[INFO] Testing: ${name}"

	echo -e "[INFO] Expected: ${sim_code}\n[INFO] Returned: ${RETCODE}"
	if ((${sim_code} == ${RETCODE}))
	then
		echo "Pass"
		printf "${test_id},${operation},Pass,${user_id},${comments}\n">> test/output/testing.csv
	else
		echo "Fail"
		printf "${test_id},${operation},Fail,${user_id},${comments}\n">> test/output/testing.csv
	fi
# done

echo "$COUNT/$NUMTESTS test cases passed."
echo -e "+--------------------+\n| ALL TESTS COMPLETE |\n+--------------------+"