#!/bin/bash
echo -e "+-------------------+\n| RUNNING ALL TESTS |\n+-------------------+"

	#any temp files to be stored in test/temp
	#output of testbench created in test/output. i.e per test logfiles
	#once all tests run, print CSV file to stdout, with each row corresponding to one execution of Simulator under test.

printf "TEST,RETCODE\n" >> test/output/log.csv

for file in test/input/*.bin
do
	name=${file##*/}	

	filename="${file%.*}.s"
	sfilename="test/input/ADD-wrap.mips.s"

	values=()

	#Read file values
	while IFS= read -r line || [[ -n "$line" ]]; do
		# reading each line
		value="${line//#}"
		values+=("$value")
	done < $filename

	no_path_filename=$(basename -- "$file")
	test_id="${no_path_filename%.mips.bin}"
	operation=${values[0]}
	sim_code=${values[1]}
	user_id=${values[2]}
	comments=${values[3]}
	getc=${values[4]}
	putc_code=${values[5]}
	
	#Run test
	binary_path="test/input/${name}"
	simulator_path="./bin/mips_simulator"

	output_s=$(echo $getc | $simulator_path $binary_path)
  RETCODE=$?

	echo ${output_s}
	echo ${RETCODE}

	if [ $RETCODE -ge 128 ]; then
		RETCODE=$((RETCODE-256))
	fi

	if [ "$RETCODE" = "$sim_code" ]; then
      if [ "$output_s" = "$putc_code" ]; then
          outcome="Pass"
					echo "Pass"
      else
				outcome="Fail"
				echo "Fail"
				message+="Output was '$output_s', expected '$putc_code'" >&2
      fi
  else
			outcome="Fail"
			echo "Fail"
			message+=" , Received output was $RETCODE wanted $sim_code"
  fi

	printf "${test_id},${operation},${outcome},${user_id},${comments},${message},${sim_code},${RETCODE}\n">> test/output/testing.csv
	NUMTESTS=0
	COUNT=0

done

echo "$COUNT/$NUMTESTS test cases passed."
echo -e "+--------------------+\n| ALL TESTS COMPLETE |\n+--------------------+"