#!/bin/bash
echo -e "+-------------------+\n| RUNNING ALL TESTS |\n+-------------------+"

	#any temp files to be stored in test/temp
	#output of testbench created in test/output. i.e per test logfiles
	#once all tests run, print CSV file to stdout, with each row corresponding to one execution of Simulator under test.

printf "TEST,RETCODE\n" >> test/output/log.csv
printf "TESTID,TEST,OUTCOME,USER_ID,COMMENTS,MESSAGE,EXPECTED,RETURNED\n">> test/output/testing.csv
NUMTESTS=0
COUNT=0

for file in test/input/*.bin
do
	name=${file##*/}	

	filename="${file%.*}.s"
	sfilename="test/input/ADD-wrap.mips.s"

	values=()

	#Read file values
	while IFS= read -r line || [[ -n "$line" ]]; do
		# reading each line
		value="${line//#}"
		values+=("$value")
	done < $filename

	no_path_filename=$(basename -- "$file")
	test_id="${no_path_filename%.mips.bin}"
	operation=${values[0]}
	sim_code=${values[1]}
	user_id=${values[2]}
	comments=${values[3]}
	getc=${values[4]}
	putc_code=${values[5]}
	
	#Run test
	binary_path="test/input/${name}"
	simulator_path="./bin/mips_simulator"

	output_s=$(echo $getc | $simulator_path $binary_path)
  RETCODE=$?

	if [ $RETCODE -ge 128 ]; then
		RETCODE=$((RETCODE-256))
	fi

	echo "[INFO] Testing: ${name}"
	if [ "$RETCODE" = "$sim_code" ]; then
      if [ "$output_s" = "$putc_code" ]; then
          outcome="Pass"
					echo "Pass"
					COUNT=$((COUNT+1))
      else
				outcome="Fail"
				echo "Fail"
				message="[INFO] Expected simoutput: '$output_s' Returned putc: '$putc_code'" >&2
				echo ${message}
      fi
  else
			outcome="Fail"
			echo "Fail"
			message="[INFO] Expected: '$RETCODE' Returned: '$sim_code'" >&2
			echo ${message}
  fi

	printf  "${name},${RETCODE}\n" >> test/output/log.csv
	printf "${test_id},${operation},${outcome},${user_id},${comments},${message},${sim_code},${RETCODE}\n">> test/output/testing.csv
	
	NUMTESTS=$((NUMTESTS+1))
done

echo "$COUNT/$NUMTESTS test cases passed."
echo -e "+--------------------+\n| ALL TESTS COMPLETE |\n+--------------------+"