#!/bin/bash
echo -e "+-------------------+\n| RUNNING ALL TESTS |\n+-------------------+"
#Input form: #bin/mips_testbench bin/mips_simulator test/input/TESTNAME

printf "TEST,RETCODE\n" >> test/output/log.csv
	
	SIM=$1 #Simulator path (passed as first argument)
	echo $SIM

	name="${2}.bin" #Test binary (passed as second argument)

	#INSERT FILE .S
	#assembly_filepath="${2}.s"
	#binary_filepath=${2}.bin
	assembly_filepath="./test/input/lwr5.s"
	binary_filepath=$2
	echo $binary_filepath
	no_path_filename=$(basename -- "$assembly_filepath")

	values=()
	#Read file values
	while IFS= read -r line || [[ -n "$line" ]]; do
		# reading each line
		value="${line//#}"
		values+=("$value")
	done < $assembly_filepath

	#Assigning fields to input test values
	test_id="${no_path_filename%.}"
	operation=${values[0]}
	sim_code=${values[1]}
	user_id=${values[2]}
	comments=${values[3]}
	getc=${values[4]}
	expected_putc=${values[5]}

	simout=$(echo $getc | $SIM "test/input/lwr5.bin")
  RETCODE=$?
	echo ${simout}
	echo ${RETCODE}
	#Run test
	# $getc | ./bin/mips_simulator test/input/${name}
	# echo ${getc}
	# if [ -f "$getc" ]; then
  #     # sim_output=$(cat $getc | "$SIM" "$binary_filepath")
	# 		simOutput=$(cat "$getc" | "$SIM" "$binary_filepath")
	# 		echo $simOutput
	# else
	# 		echo ${getc}
	# 	  simOutput=$(cat "$getc" | "$SIM" "$binary_filepath")
	# 		echo $simOutput
  # fi

	if [ $RETCODE -ge 128 ]; then
		RETCODE=$((RETCODE-256))
	fi
	echo $RETCODE

	NUMTESTS=0
	COUNT=0

	printf  "${name},${RETCODE}\n" >> test/output/log.csv
	echo "[INFO] Testing: ${name}"

	echo -e "[INFO] Expected: ${sim_code}\n[INFO] Returned: ${RETCODE}"
	if ((${sim_code} == ${RETCODE}))
	then
		echo "Pass"
		printf "${test_id},${operation},Pass,${user_id},${comments}\n">> test/output/testing.csv
	else
		echo "Fail"
		printf "${test_id},${operation},Fail,${user_id},${comments}\n">> test/output/testing.csv
	fi
# done

echo "$COUNT/$NUMTESTS test cases passed."
echo -e "+--------------------+\n| ALL TESTS COMPLETE |\n+--------------------+"